form:
  label: Default Page Dialog
  tabs:
    - name: tabMain
      label: Page Content
      fields:
       
        - name: title
          class: info.magnolia.ui.form.field.definition.TextFieldDefinition
          label: Page Title
          description: Define the Page's title.
          required: true
 
        - name: abstract
          class: info.magnolia.ui.form.field.definition.TextFieldDefinition
          label: Abstract
          description: Add an Abstract of the Page.
          rows: 5
           
    - name: tabMeta
      label: Page Meta Data
      fields:
       
        - name: keywords
          class: info.magnolia.ui.form.field.definition.TextFieldDefinition
          label: Keywords
          description: The keywords used in the html header in the meta tag 'meta name=keywords'.
          rows: 3
          i18n: true
           
        - name: description
          class: info.magnolia.ui.form.field.definition.TextFieldDefinition
          label: Description
          description: The description used in the html header in the meta tag 'meta name=description'. Fallback is the page's abstract.
          rows: 5
          i18n: true         
 
actions: !include /training-templating-website/includes/dialogs/actions.yaml 
